# Generated by Django 5.0.3 on 2025-05-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0004_alter_curso_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudante",
            name="celular",
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
